/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        display: ['"DM Serif Display"', 'Georgia', 'serif'],
        serif: ['"Lora"', 'Georgia', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        // Clean zinc-based neutrals — no warm parchment
        surface: {
          50:  '#fafafa',
          100: '#f4f4f5',
          200: '#e4e4e7',
          300: '#d4d4d8',
          400: '#a1a1aa',
          500: '#71717a',
          600: '#52525b',
          700: '#3f3f46',
          800: '#27272a',
          900: '#18181b',
          950: '#09090b',
        },
        // Accent: saturated amber — warm, authoritative, distinctive
        amber: {
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
        },
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '1rem' }],
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body':         theme('colors.surface.700'),
            '--tw-prose-headings':     theme('colors.surface.950'),
            '--tw-prose-lead':         theme('colors.surface.600'),
            '--tw-prose-links':        theme('colors.amber.700'),
            '--tw-prose-bold':         theme('colors.surface.900'),
            '--tw-prose-counters':     theme('colors.surface.500'),
            '--tw-prose-bullets':      theme('colors.surface.400'),
            '--tw-prose-hr':           theme('colors.surface.200'),
            '--tw-prose-quotes':       theme('colors.surface.900'),
            '--tw-prose-quote-borders': theme('colors.amber.500'),
            '--tw-prose-captions':     theme('colors.surface.500'),
            '--tw-prose-code':         theme('colors.surface.900'),
            '--tw-prose-pre-code':     theme('colors.surface.100'),
            '--tw-prose-pre-bg':       theme('colors.surface.900'),
            '--tw-prose-th-borders':   theme('colors.surface.300'),
            '--tw-prose-td-borders':   theme('colors.surface.200'),
            '--tw-prose-invert-body':         theme('colors.surface.300'),
            '--tw-prose-invert-headings':     theme('colors.surface.50'),
            '--tw-prose-invert-lead':         theme('colors.surface.400'),
            '--tw-prose-invert-links':        theme('colors.amber.400'),
            '--tw-prose-invert-bold':         theme('colors.surface.100'),
            '--tw-prose-invert-counters':     theme('colors.surface.400'),
            '--tw-prose-invert-bullets':      theme('colors.surface.600'),
            '--tw-prose-invert-hr':           theme('colors.surface.800'),
            '--tw-prose-invert-quotes':       theme('colors.surface.100'),
            '--tw-prose-invert-quote-borders': theme('colors.amber.500'),
            '--tw-prose-invert-captions':     theme('colors.surface.400'),
            '--tw-prose-invert-code':         theme('colors.surface.100'),
            '--tw-prose-invert-pre-code':     theme('colors.surface.300'),
            '--tw-prose-invert-pre-bg':       'rgb(0 0 0 / 40%)',
            '--tw-prose-invert-th-borders':   theme('colors.surface.700'),
            '--tw-prose-invert-td-borders':   theme('colors.surface.800'),
            maxWidth: 'none',
            fontFamily: theme('fontFamily.serif').join(', '),
            fontSize: '1.0625rem',
            lineHeight: '1.85',
            'p': { marginTop: '1.35em', marginBottom: '1.35em' },
            'h1': { fontFamily: theme('fontFamily.display').join(', '), fontWeight: '400', letterSpacing: '-0.02em' },
            'h2': { fontFamily: theme('fontFamily.display').join(', '), fontWeight: '400', letterSpacing: '-0.015em' },
            'h3': { fontFamily: theme('fontFamily.display').join(', '), fontWeight: '400', letterSpacing: '-0.01em' },
            'h4': { fontFamily: theme('fontFamily.sans').join(', '), fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.04em', fontSize: '0.8125rem' },
            'blockquote p': { fontStyle: 'italic' },
            'a': { textDecoration: 'underline', textDecorationColor: 'currentColor', textUnderlineOffset: '3px' },
            'table': { fontFamily: theme('fontFamily.sans').join(', '), fontSize: '0.875rem' },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
