/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        serif: ['"Source Serif 4"', 'Georgia', 'serif'],
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        parchment: {
          50: '#faf8f3',
          100: '#f5f0e8',
          200: '#ede4d3',
          300: '#ddd0b8',
          400: '#c9b592',
          500: '#b89b72',
          600: '#a58460',
          700: '#896b4d',
          800: '#6f5540',
          900: '#5a4535',
        },
        ink: {
          50: '#f4f4f2',
          100: '#e8e7e3',
          200: '#d2d0c9',
          300: '#b4b1a8',
          400: '#908d82',
          500: '#747168',
          600: '#5e5c53',
          700: '#4d4b44',
          800: '#3a3834',
          900: '#2a2926',
          950: '#1a1917',
        },
        gold: {
          300: '#f0d080',
          400: '#e8c050',
          500: '#d4a820',
          600: '#b88f10',
          700: '#9a7608',
        },
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.ink.800'),
            '--tw-prose-headings': theme('colors.ink.950'),
            '--tw-prose-lead': theme('colors.ink.700'),
            '--tw-prose-links': theme('colors.gold.700'),
            '--tw-prose-bold': theme('colors.ink.900'),
            '--tw-prose-counters': theme('colors.ink.500'),
            '--tw-prose-bullets': theme('colors.ink.400'),
            '--tw-prose-hr': theme('colors.ink.200'),
            '--tw-prose-quotes': theme('colors.ink.900'),
            '--tw-prose-quote-borders': theme('colors.gold.500'),
            '--tw-prose-captions': theme('colors.ink.500'),
            '--tw-prose-code': theme('colors.ink.900'),
            '--tw-prose-pre-code': theme('colors.parchment.100'),
            '--tw-prose-pre-bg': theme('colors.ink.900'),
            '--tw-prose-th-borders': theme('colors.ink.300'),
            '--tw-prose-td-borders': theme('colors.ink.200'),
            '--tw-prose-invert-body': theme('colors.parchment.200'),
            '--tw-prose-invert-headings': theme('colors.parchment.50'),
            '--tw-prose-invert-lead': theme('colors.parchment.300'),
            '--tw-prose-invert-links': theme('colors.gold.400'),
            '--tw-prose-invert-bold': theme('colors.parchment.100'),
            '--tw-prose-invert-counters': theme('colors.parchment.400'),
            '--tw-prose-invert-bullets': theme('colors.parchment.500'),
            '--tw-prose-invert-hr': theme('colors.ink.700'),
            '--tw-prose-invert-quotes': theme('colors.parchment.100'),
            '--tw-prose-invert-quote-borders': theme('colors.gold.500'),
            '--tw-prose-invert-captions': theme('colors.parchment.400'),
            '--tw-prose-invert-code': theme('colors.parchment.100'),
            '--tw-prose-invert-pre-code': theme('colors.parchment.300'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.ink.600'),
            '--tw-prose-invert-td-borders': theme('colors.ink.700'),
            maxWidth: 'none',
            fontFamily: theme('fontFamily.serif').join(', '),
            fontSize: '1.0625rem',
            lineHeight: '1.8',
            'p': { marginTop: '1.25em', marginBottom: '1.25em' },
            'h1, h2, h3, h4': { fontFamily: theme('fontFamily.serif').join(', '), fontWeight: '700' },
            'blockquote p': { fontStyle: 'italic' },
            'a': { textDecoration: 'underline', textDecorationColor: 'currentColor', textUnderlineOffset: '3px' },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
